### ISSUE TITLE
Does not work for me

### ISSUE THREAD

**Issue by johann-petrak** [JenoDK/bracket-selection#8]
Using Pycharm community 2020.2 and Bracket Selection 1.5 on Ubuntu Linux 18.04

Pointing at an opening bracket/parenthesis, closing or between and holding Alt (left alt or right altgr) and double clicking does nothing.

Not sure what "alt button 1"  is supposed to mean in the description. I have a standard three button mouse. 

Sounds like a great idea, but unfortunately does not seem to work at all for me.

**Comment by JenoDK** [comment]
I've pushed a new 1.6 update where I discovered a bug where the selection would not work properly if other opening and closing brackets are found between the initial one you want.

This might solve the issue you're having, could you please try it out once Jetbrains approves the 1.6 update?

FYI 'alt button 1' is hold alt and left double click in Jetbrains keybinding terms.

### Some technical info regarding the bug:
`if (x != vector1.size() && x != vector2.size());`
f.e. if your cursor in right before 'vector2' and you were to alt double left click it wouldn't select anything since it was backtracking and trying to find the first opening bracket which in this case is the 'vector1.size()' which is wrong ofcourse.

**Comment by johann-petrak** [comment]
Thanks for this! 
I think my problem may actually be a different one thought: On (my?) Linux (Ubuntu with the Mate desktop manager), Alt+LeftClickAndHold is assigned to moving the focused window, and I think that prevents the Alt+LeftDoubleClick event to get passed on to the app at all. 
TBH I am not sure how to prevent that or how to reassign this in either Linux or Pycharm to some other key+click combination (e.g. LeftWindowsKey+Click is probably unassigned)

**Comment by JenoDK** [comment]
Aha that would explain it, you can always change the key binding to something of your on preference.
![image](https://user-images.githubusercontent.com/11025460/103675287-0dbf9680-4f80-11eb-88a8-642a8e662bf8.png)

**Comment by johann-petrak** [comment]
Thank you, I changed it to Ctrl+Button3Doubleclick and it works!
